services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - default-network
    volumes:
      - mysql_data:/var/lib/mysql

  spring:
    image: matheushdas/restful-api-example
    build: ..
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/exampledb?useTimezone=true&serverTimezone=UTC
      spring.datasource.username: exampleuser
      spring.datasource.password: examplepass
    ports:
      - "8080:8080"
    networks:
      - default-network
    command:
      - mvn spring-boot:run
    depends_on:
      - mysql

networks:
  default-network:
    driver: bridge
volumes:
  mysql_data:
